### ISSUE TITLE
Se puede agregar más de un equipo a la cuenta de un staff

### ISSUE THREAD

**Issue by nicolascuadram** [urzuaf/CS2024_1_Ya_cabros#133]
Un staff solo debe estar asociado a un único equipo, actualmente al momento de crear el equipo es necesario recargar la página para poder acceder al resto de funciones del staff relacionadas al equipo, pero si no se cambia de página es posible seguir agregando equipos .Algunas soluciones podrían ser:
- Evitar agregar datos en la base de datos si ésta ya tiene datos asociados, lo que requiere una lógica distinta que en el formulario de modificar los datos existentes.
- También sería buena idea redirigir inmediatamente a otra página al momento de crear el equipo, puede ser al index o al perfil del equipo.

![a](https://github.com/urzuaf/CS2024_1_Ya_cabros/assets/112027693/745ed12b-4c26-4150-a492-a6c7ba37f753)

**Comment by tomitox29** [comment]
Issue terminada
