### ISSUE TITLE
Errores en modo claro y oscuro

### ISSUE THREAD

**Issue by nicolascuadram** [urzuaf/CS2024_1_Ya_cabros#21]
Errores en modo claro y oscuro en páginas login y registro.

**Comment by nicolascuadram** [comment]
Imagen del error

![1](https://github.com/urzuaf/CS2024_1_Ya_cabros/assets/112027693/f887181c-808b-4a7c-ac17-79605b64607c)

**Comment by urzuaf** [comment]
Solucionado

**Comment by nicolascuadram** [comment]
PR de la solución.

https://github.com/urzuaf/CS2024_1_Ya_cabros/pull/20
