### ISSUE TITLE
Arreglar el footer

### ISSUE THREAD

**Issue by urzuaf** [urzuaf/CS2024_1_Ya_cabros#62]
Agregar los iconos, aunque los links no sean funcionales, agregar los iconos para no tener esos circulos en blanco

**Comment by urzuaf** [comment]
Los links del footer son "[Nosotros](javascript:void(0))
    [Blog](javascript:void(0))
    [Equipo](javascript:void(0))
    [Carreras](javascript:void(0))
    [Support](javascript:void(0))"
No tenemos esas páginas, cambiarlos por algunas que si existan

**Comment by Jvviers** [comment]
Terminada
