### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by urzuaf** [urzuaf/CS2024_1_Ya_cabros#65]
- EL navbar debe mostrar los datos del usuario logeado.
- Cambiar las notificaciones al navbar
- Agregar un botón que permita iniciar sesión si el usuario no está logeado
- Acomodar los estilos del navbar a los del documento de diseño

**Comment by urzuaf** [comment]
Yo me encargo de pasar las notificaciones

**Comment by Jvviers** [comment]
Listo la interfaz para logear o registrar en un futuro cuando se cree la lógica en el backend
