### ISSUE TITLE
Agregar jugador

### ISSUE THREAD

**Issue by urzuaf** [urzuaf/CS2024_1_Ya_cabros#68]
- Se necesita feedback para todas las operaciones de esta página. Ya sea que fallen o estén correctas

**Comment by ErikSoza** [comment]
Se agrega dentro de la funciones del .js y .svelte la forma de dar un feedback al usuario cada vez que realice una accion dentro de las opciones de agregar jugador.

**Comment by ErikSoza** [comment]
Se agrega dentro de la funciones del .js y .svelte la forma de dar un feedback al usuario cada vez que realice una accion dentro de las opciones de agregar jugador. [40 min]
